In [1]:
import numpy as np
import scipy.linalg as sla

### Exercício 1.1
Classifique os sistemas abaixo com relação a quantidade e existência de soluções.

In [2]:
def verifMatrix(matrixA, matrixB):
    rankA = np.linalg.matrix_rank(matrixA)
    rankPosto = np.linalg.matrix_rank(np.c_[matrixA, matrixB])
    shapeMatrixA = matrixA.shape[1]
    
    # se A = B e B = C, C = A
    if rankA == rankPosto and rankPosto == shapeMatrixA:
        print("Sistema possível determinado")
        #rank(Aposto) = rank(A) < n
    elif rankA == rankPosto and rankA < shapeMatrixA:
        print("Sistema possível indeterminado")
    else:
        print("Sistema impossível")

#### a)
$x + 2y + 3z = 1$

$4x + 5y + 6z = 1$

$7x + 8y + 9z = 1$

In [3]:
Aa = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ba = np.array([1, 1, 1])
print("A:")
verifMatrix(Aa, ba)

A:
Sistema possível indeterminado


#### b)
$2x + 3y = 10$

$−4x − 6y = −10$

In [4]:
Ab = np.array([[2, 3], [-4, -6]])
bb = np.array([10, -10])
print("B:")
verifMatrix(Ab, bb)

B:
Sistema impossível


### Exercício 1.2
Repita o exemplo 3.2 acima, porém fazendo cada passo da execução de forma explícita, comparando como o algoritmo 1.2 e a função sist_lin_tri_sup funcionam. Sugestão: faça isso de forma manuscrita. Ajudará a entender melhor cada passo.

Os sistemas triangulares inferiores tem a forma algébrica do tipo

$3x_{1} + 4x_{2} − 5x_{3} + x_{4} = −10$<br/>
$x_{2} + x_{3} − 2x_{4} = −1$<br/>
$4x_{3} − 5x_{4} = 3$<br/>
$2x_{4} = 2$<br/>

em que a matriz de coeficientes

$
	\begin{bmatrix} 
        3 & 4 & -5 & 1 \\
        0 & 1 & 1 & -2 \\
        0 & 1 & 4 & -5 \\
        0 & 0 & 0 & 2 \\
	\end{bmatrix}
	\quad
    \times
    \begin{bmatrix} 
        -10 \\
        -2 \\
        3 \\
        2 \\
	\end{bmatrix}
	\quad
$

é uma matriz triangular inferior, cujos elementos acima da diagonal principal são nulos, isto é,
$a_{ij} = 0$ para todo $i < j$.

A ideia da substituição usada nos sistemas triangulares superiores é exatamente a
mesma para sistemas triangulares inferiores, diferenciando-se apenas que, ao invés de começar
pela incógnita de maior índice, inicia-se pela de menor índice, sendo esse método, por esse
motivo, referido como substituição progressiva

Dessa forma a primeira incógnita encontrada será

$x1 = \frac{b_1}{a_{11}}$

cujo valor pode ser usado na segunda equação para encontrar a segunda incógnita, fazendo

$x2 = \frac{b_2 − a_{21}x_1}{a_{22}}
$

e esses dois valores podem ser usados na terceira equação para encontrar o termo $x_3$ e assim
por diante, até que, na última equação, os $n − 1$ primeiros termo da solução serão conhecidos e
possibilitarão encontrar o termo $x_n$.


In [7]:
def sist_lin_tri_sup(A,b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

In [8]:
A = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])
print(sist_lin_tri_sup(A, b))

[ 1. -1.  2.  1.]


$3x_{1} = 4$<br/>
$2x_{1} + x_{2} = 2$<br/>
$x_{1} + x_{3} = 4$<br/>
$x_{1} + x_{2} + x_{3} + x_{4} = 2$<br/>

$
	\begin{bmatrix} 
        3 & 0 & 0 & 0 \\
        2 & 1 & 0 & 0 \\
        1 & 0 & 1 & 0 \\
        1 & 1 & 1 & 1 \\
	\end{bmatrix}
	\quad
    \times
    \begin{bmatrix} 
        4 \\
        2 \\
        4 \\
        2 \\
	\end{bmatrix}
	\quad
$

### Exercício 1.3
Repita o exemplo 3.3 acima, porém fazendo cada passo da execução de forma explícita, comparando como o algoritmo 1.3 e a função sist_lin_tri_inf funcionam. Use a mesma sugestão do exercício anterior

In [25]:
def sist_lin_tri_inf(A,b):
    n = len(b)
    x = np.empty(n)
    x[0] = b[0]/A[0, 0]
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]   
    return x

In [29]:
def calcLinear(A, b):
    if checkDiagonal(A) :
        print(f"\n{b / A.diagonal()}")
    elif checkSup(A) :
        print(f"\n{sist_lin_tri_sup(A, b)}")
    elif checkInf(A) :
        print(f"\n{sist_lin_tri_inf(A, b)}")

In [30]:
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
B = np.array([4,2,4,2])

In [31]:
print(calcLinear(A, B))


[ 1.33333333 -0.66666667  2.66666667 -1.33333333]
None


### Exercício 1.4
Implemente uma função, cujos parâmetros de entrada sejam somente a matriz de coeficientes e o vetor de termos independentes e que calcule o vetor solução para qualquer um dos casos triviais vistos aqui. Atente para o fato de que a própria função terá de verificar se a matriz de coeficientes é diagonal, triangular superior ou inferior e não o usuário.

In [13]:
def checkDiagonal(A) :
    n = len(A)
    for i in range(n) :
        for j in range(n) :
            if i != j and A[i, j] != 0:
                return False
    return True


In [14]:
def checkSup(A) :
    n = len(A)
    for i in range(n) :
        for j in range(i) :
            if A[i, j] != 0 :
                return False
    return True

In [15]:
def checkInf(A) :
    n = len(A)
    for i in range(n) :
        for j in range(i + 1, n) :
            if A[i, j] != 0 :
                return False
    return True

In [16]:
def calcLinear(A, b):
    if checkDiagonal(A) :
        print(f"Diagonal.\n{b / A.diagonal()}")
    elif checkSup(A) :
        print(f"Matriz superior.\n{sist_lin_tri_sup(A, b)}")
    elif checkInf(A) :
        print(f"Matriz inferior.\n{sist_lin_tri_inf(A, b)}")
        

In [20]:
Aa = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])
ba = np.array([-10,-1,3,2])
calcLinear(Aa, ba)
print()

Matriz superior.
[ 1. -1.  2.  1.]



In [21]:
Ab = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
bb = np.array([4,2,4,2])
calcLinear(Ab, bb)
print()

Matriz inferior.
[ 1.33333333 -0.66666667  2.66666667 -1.33333333]



In [22]:
Ac = np.diag([1,4,2])
bc = np.array([4, 2, 2])
calcLinear(Ac,bc)

Diagonal.
[4.  0.5 1. ]
